version: "3"
services:
  traefik:
    container_name: traefik

    image: traefik:latest

    command:
      - --api.insecure=true
      - --providers.docker

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"

  # app:
  #   build: .
  #   environment:
  #     NODE_ENV: development
  #     PORT: 3000
  #   ports:
  #     - "3000:3000"
  #   command: npm run dev
  #   volumes:
  #     - .:/app/
  #     - /app/node_modules
