version: "3.5"
services:
  traefik:
    volumes:
      - ./config/traefik.dev.yaml:/etc/traefik/traefik.yaml

    labels:
      #### Labels define the behavior and rules of the traefik proxy for this container ####
      - "traefik.http.routers.traefik.entrypoints=web"

    ports:
      - "80:80"

  nodejs:
    build:
      context: ./nodejs
      dockerfile: Dockerfile.dev

    labels:
      #### Labels define the behavior and rules of the traefik proxy for this container ####
      - "traefik.http.routers.nodejs.entrypoints=web"

  flask:
    build: ./flask

    labels:
      - "traefik.http.routers.flask.entrypoints=web"

  reactjs:
    build:
      context: ./reactjs
      dockerfile: Dockerfile.dev

    depends_on:
      - nodejs

    networks:
      - traefik-proxy

    volumes:
      - /app/node_modules # use containers node_modules
      - ./reactjs:/app

    labels:
      - "traefik.http.routers.reactjs.entrypoints=web"
