[log]
  level = "DEBUG"

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.web.http.redirections.entryPoint]
    to = "websecure"
    scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.letsencrypt.acme]
  email = "yourmail@domain.com"
  storage = "/letsencrypt/acme.json"
  [certificatesResolvers.letsencrypt.acme.tlsChallenge]


[api]
  dashboard = true

[providers.docker]
  exposedByDefault = false
  network = "traefik-global-proxy" # this is really important when you have multiple networks on a single container. This will tell Traefik to always look for network traefik-global-proxy and not any other internal networks.

# defaultEntryPoints = ["http", "https"]
# logLevel = "INFO"

# sendAnonymousUsage = false

# [docker]
#   endpoint = "unix:///var/run/docker.sock"
#   exposedByDefault = false

# # enabling api is not absolutely necessary, it is needed only if you need dashboard.
# [api]
# dashboard = true
# entrypoint = "dashboard"


# [entryPoints]
#   [entryPoints.http]
#   address = ":80"
#     [entryPoints.http.redirect]
#     entryPoint = "https"

#   [entryPoints.https]
#   address = ":443"
#     [entryPoints.https.tls]
#     [[entryPoints.https.tls.certificates]]
#     certFile = "/certs/tls.crt"
#     keyFile = "/certs/tls.key"

#   [entryPoints.dashboard]
#   address = ":8080"

#     # [entryPoints.dashboard.auth.basic]
#     # # admin/secret
#     # users = []