services:
  frpc:
    image: fatedier/frpc:v0.61.0
    container_name: frpc
    network_mode: host # necessary !!
    volumes:
      - ./frpc.toml:/etc/frpc.toml
    entrypoint: ["/usr/bin/frpc"]
    command: ["-c", "/etc/frpc.toml"]
    restart: unless-stopped
    ports:
      - "7000:7000" # Main FRP connection port
