version: "3"

services:
  db:
    image: mysql:5.7
    container_name: db

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - ./db_data:/var/lib/mysql

    networks:
      - wpsite

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wordpress_php

    depends_on:
      - db
    restart: always
    ports:
      - "8080:80"

    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    labels:
      - "traefik.enable=true" # <== Enable traefik on itself to view dashboard and assign subdomain to view it
      - "traefik.port=8080"
      - "traefik.http.routers.wordpress_php.entrypoints=websecure" # <== Defining entrypoint for https
      - "traefik.http.routers.wordpress_php.tls.certresolver=mytlschallenge" # <== Defining certsresolvers for https
      - "traefik.http.routers.wordpress_php.rule=Host(`wordpress_php.${DOMAIN_URL}`)" # domain to expose on

    networks:
      - traefik-proxy
      - wpsite

  wordpress:
    image: wordpress:latest
    container_name: wordpress

    depends_on:
      - db
    ports:
      - "8000:80"
    restart: always

    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}

    volumes: ["./data/:/var/www/html"]

    labels:
      - "traefik.enable=true" # <== Enable traefik on itself to view dashboard and assign subdomain to view it
      - "traefik.port=8000"
      - "traefik.http.routers.wordpress.entrypoints=websecure" # <== Defining entrypoint for https
      - "traefik.http.routers.wordpress.tls.certresolver=mytlschallenge" # <== Defining certsresolvers for https
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.${DOMAIN_URL}`)" # domain to expose on

    networks:
      - traefik-proxy
      - wpsite

networks:
  traefik-proxy:
    external: true

  wpsite:

volumes:
  db_data:
