version: "3.5"
services:
  traefik:
    volumes:
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml
      - ./config/dynamic.yaml:/dynamic.yaml # <== Volume for dynamic conf file

    labels:
      #### Labels define the behavior and rules of the traefik proxy for this container ####
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=mytlschallenge"
      # - "traefik.http.routers.traefik.middlewares=auth" # enable password auth
      # - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$Dqo7TC2B$$23bAWltXXzx01XUbq2BU50" # substitute with your htpasswd string and escape dollar signs!

    ports:
      - "80:80"
      - "443:443"

  nodejs:
    build: ./nodejs

    #   # healthcheck:
    #   #   test: curl http://127.0.0.1:3000 -s -f -o /dev/null || exit 1
    #   #   interval: 10s
    #   #   timeout: 10s
    #   #   retries: 3

    labels:
      #### Labels define the behavior and rules of the traefik proxy for this container ####
      - "traefik.http.routers.nodejs.entrypoints=websecure" # <== Defining entrypoint for https
      - "traefik.http.routers.nodejs.tls.certresolver=mytlschallenge" # <== Defining certsresolvers for https

      # - "traefik.backend.healthcheck.path=/"
      # - "traefik.backend.healthcheck.interval=10s"
      # - "traefik.backend.healthcheck.timeout=10s"

  flask:
    build: ./flask

    labels:
      - "traefik.http.routers.flask.entrypoints=websecure" # <== Defining entrypoint for https
      - "traefik.http.routers.flask.tls.certresolver=mytlschallenge" # <== Defining certsresolvers for https

  reactjs:
    build: ./reactjs

    depends_on:
      - nodejs

    labels:
      - "traefik.http.routers.reactjs.entrypoints=websecure" # if you named your 443 entrypoint differently than webscure, substitute it here!
      - "traefik.http.routers.reactjs.tls.certresolver=mytlschallenge"
