version: "3.5"
services:
  nodejs:
    build: ./nodejs
    container_name: nodejs
    restart: unless-stopped

    labels:
      #### Labels define the behavior and rules of the traefik proxy for this container ####
      - "traefik.enable=true" # <== Enable traefik to proxy this container
      # - "traefik.frontend.rule=PathPrefix: /api"

      - "traefik.http.routers.nodejs.rule=Host(`api.${DOMAIN_URL}`)" # <== Your Domain Name for the https rule

    volumes:
      - /app/node_modules
      - ./nodejs:/app

    networks:
      - traefik-proxy

  flask:
    build: ./flask
    container_name: flask
    restart: unless-stopped

    labels:
      - "traefik.enable=true" # <== Enable traefik to proxy this container
      - "traefik.http.routers.flask.rule=Host(`api.blog.${DOMAIN_URL}`)" # <== Your Domain Name for the https rule

    volumes:
      - ./flask:/app

    networks:
      - traefik-proxy

  reactjs:
    build: ./reactjs
    container_name: reactjs

    depends_on:
      - nodejs

    networks:
      - traefik-proxy

    volumes:
      - /app/node_modules # use containers node_modules
      - ./reactjs:/app

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reactjs.rule=Host(`${DOMAIN_URL}`)" # domain to expose on

networks:
  traefik-proxy:
    name: traefik-proxy
    external: true
