version: "3.5"
services:
  nodejs:
    build: ./nodejs

    #   # healthcheck:
    #   #   test: curl http://127.0.0.1:3000 -s -f -o /dev/null || exit 1
    #   #   interval: 10s
    #   #   timeout: 10s
    #   #   retries: 3

    labels:
      #### Labels define the behavior and rules of the traefik proxy for this container ####
      - "traefik.http.routers.nodejs.entrypoints=websecure" # <== Defining entrypoint for https
      - "traefik.http.routers.nodejs.tls.certresolver=mytlschallenge" # <== Defining certsresolvers for https

      # - "traefik.backend.healthcheck.path=/"
      # - "traefik.backend.healthcheck.interval=10s"
      # - "traefik.backend.healthcheck.timeout=10s"

  flask:
    build: ./flask

    labels:
      - "traefik.http.routers.flask.entrypoints=websecure" # <== Defining entrypoint for https
      - "traefik.http.routers.flask.tls.certresolver=mytlschallenge" # <== Defining certsresolvers for https

  reactjs:
    build: ./reactjs

    depends_on:
      - nodejs

    labels:
      - "traefik.http.routers.reactjs.entrypoints=websecure" # if you named your 443 entrypoint differently than webscure, substitute it here!
      - "traefik.http.routers.reactjs.tls.certresolver=mytlschallenge"
